[build]
command = "yarn build"
publish = "dist"
functions = "functions-build"

[dev]
publish = "dist"

[[redirects]]
from = "/api/v1/*"
to = "/.netlify/functions/:splat"
status = 200

[functions]
node_bundler = "esbuild"
directory = "functions/"
