[build]
command = "yarn build"
publish = "functions-build/"
functions = "functions"

[[redirects]]
from = "/api/v1/*"
to = "/.netlify/functions/:splat"
status = 200

[functions]
node_bundler = "esbuild"
directory = "functions/"
