[build]
# This is the directory is publishing to netlify's CDN
publish = "dist"
# functions build directory
functions = "functions-build"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/v1/*"
to = "/.netlify/functions/:splat"
status = 200
